set -e
true
true
/home/vscode/miniforge3/envs/bioinfo/bin/spades-hammer /workspaces/Bioinfo_PPGSis_2026.1/1_dados/1.brutos/aula_04/spades/corrected/configs/config.info
/home/vscode/miniforge3/envs/bioinfo/bin/python3 /home/vscode/miniforge3/envs/bioinfo/share/spades/spades_pipeline/supplemetary/compress_all.py --input_file /workspaces/Bioinfo_PPGSis_2026.1/1_dados/1.brutos/aula_04/spades/corrected/corrected.yaml --ext_python_modules_home /home/vscode/miniforge3/envs/bioinfo/share/spades --max_threads 16 --output_dir /workspaces/Bioinfo_PPGSis_2026.1/1_dados/1.brutos/aula_04/spades/corrected --gzip_output
true
true
/home/vscode/miniforge3/envs/bioinfo/bin/spades-core /workspaces/Bioinfo_PPGSis_2026.1/1_dados/1.brutos/aula_04/spades/K21/configs/config.info
/home/vscode/miniforge3/envs/bioinfo/bin/spades-core /workspaces/Bioinfo_PPGSis_2026.1/1_dados/1.brutos/aula_04/spades/K33/configs/config.info
/home/vscode/miniforge3/envs/bioinfo/bin/spades-core /workspaces/Bioinfo_PPGSis_2026.1/1_dados/1.brutos/aula_04/spades/K55/configs/config.info
/home/vscode/miniforge3/envs/bioinfo/bin/spades-core /workspaces/Bioinfo_PPGSis_2026.1/1_dados/1.brutos/aula_04/spades/K77/configs/config.info
/home/vscode/miniforge3/envs/bioinfo/bin/spades-core /workspaces/Bioinfo_PPGSis_2026.1/1_dados/1.brutos/aula_04/spades/K99/configs/config.info
/home/vscode/miniforge3/envs/bioinfo/bin/spades-core /workspaces/Bioinfo_PPGSis_2026.1/1_dados/1.brutos/aula_04/spades/K127/configs/config.info
/home/vscode/miniforge3/envs/bioinfo/bin/python3 /home/vscode/miniforge3/envs/bioinfo/share/spades/spades_pipeline/supplemetary/copy_files.py /workspaces/Bioinfo_PPGSis_2026.1/1_dados/1.brutos/aula_04/spades/K127/before_rr.fasta /workspaces/Bioinfo_PPGSis_2026.1/1_dados/1.brutos/aula_04/spades/before_rr.fasta /workspaces/Bioinfo_PPGSis_2026.1/1_dados/1.brutos/aula_04/spades/K127/assembly_graph_after_simplification.gfa /workspaces/Bioinfo_PPGSis_2026.1/1_dados/1.brutos/aula_04/spades/assembly_graph_after_simplification.gfa /workspaces/Bioinfo_PPGSis_2026.1/1_dados/1.brutos/aula_04/spades/K127/final_contigs.fasta /workspaces/Bioinfo_PPGSis_2026.1/1_dados/1.brutos/aula_04/spades/contigs.fasta /workspaces/Bioinfo_PPGSis_2026.1/1_dados/1.brutos/aula_04/spades/K127/first_pe_contigs.fasta /workspaces/Bioinfo_PPGSis_2026.1/1_dados/1.brutos/aula_04/spades/first_pe_contigs.fasta /workspaces/Bioinfo_PPGSis_2026.1/1_dados/1.brutos/aula_04/spades/K127/strain_graph.gfa /workspaces/Bioinfo_PPGSis_2026.1/1_dados/1.brutos/aula_04/spades/strain_graph.gfa /workspaces/Bioinfo_PPGSis_2026.1/1_dados/1.brutos/aula_04/spades/K127/scaffolds.fasta /workspaces/Bioinfo_PPGSis_2026.1/1_dados/1.brutos/aula_04/spades/scaffolds.fasta /workspaces/Bioinfo_PPGSis_2026.1/1_dados/1.brutos/aula_04/spades/K127/scaffolds.paths /workspaces/Bioinfo_PPGSis_2026.1/1_dados/1.brutos/aula_04/spades/scaffolds.paths /workspaces/Bioinfo_PPGSis_2026.1/1_dados/1.brutos/aula_04/spades/K127/assembly_graph_with_scaffolds.gfa /workspaces/Bioinfo_PPGSis_2026.1/1_dados/1.brutos/aula_04/spades/assembly_graph_with_scaffolds.gfa /workspaces/Bioinfo_PPGSis_2026.1/1_dados/1.brutos/aula_04/spades/K127/assembly_graph.fastg /workspaces/Bioinfo_PPGSis_2026.1/1_dados/1.brutos/aula_04/spades/assembly_graph.fastg /workspaces/Bioinfo_PPGSis_2026.1/1_dados/1.brutos/aula_04/spades/K127/final_contigs.paths /workspaces/Bioinfo_PPGSis_2026.1/1_dados/1.brutos/aula_04/spades/contigs.paths
true
/home/vscode/miniforge3/envs/bioinfo/bin/python3 /home/vscode/miniforge3/envs/bioinfo/share/spades/spades_pipeline/supplemetary/breaking_scaffolds_script.py --result_scaffolds_filename /workspaces/Bioinfo_PPGSis_2026.1/1_dados/1.brutos/aula_04/spades/scaffolds.fasta --misc_dir /workspaces/Bioinfo_PPGSis_2026.1/1_dados/1.brutos/aula_04/spades/misc --threshold_for_breaking_scaffolds 3
true
